### PR TITLE
for real phone test demo

### PR DESCRIPTION
**Pull request by Dong-Jie-Chen**

### CODE REVIEW

**Review by rmsepic — APPROVED** [review]
So this is actually getting the number from our card?

This looks really good.

**Comment by Dong-Jie-Chen** [comment]
It won't get your real card number though you will see your card number on the screen. The card number sent to the backend will be "4242 4242 4242 4242".

**Comment by Dong-Jie-Chen** [comment]
The purpose I show the real card number on the screen is to show the CardScan has been used successfully.

**Review by rmsepic — CHANGES_REQUESTED** [review]
This is not apart of this PR exactly so I can't highlight the code, but on line 121 in PaymentViewController setData should be updateData, setData overwrites all the other values

**Comment by Dong-Jie-Chen** [comment]
Thanks! I changed the code to use updateData.

**Review by rmsepic — APPROVED** [review]

**Pull request merged**
